version: "3"

services:
  backend:
    build: ./backend_librarymangement
    ports:
      - 5000:5000
    depends_on:
      - redis-server

  frontend:
    build: ./online-library
    ports:
      - 80:3000
    depends_on:
      - backend

  redis-server:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/rdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  node_modules:
